### ISSUE TITLE
Raygui Integration

### ISSUE THREAD

**Issue by xiroV** [xiroV/game-tools#30]
Windows, textfields, buttons etc. should use raygui components.

https://github.com/raysan5/raygui

**Comment by Tiggles** [comment]
Raygui has the zlib license. Should we give attribution somewhere?

> 1. The origin of this software must not be misrepresented; you must not claim that you 
>  wrote the original software. If you use this software in a product, an acknowledgment 
>  in the product documentation would be appreciated but is not required.

Also, how do we include it? Just copy paste the file and update on new features/bugfixes?
